preload = /home/tsantos/.local/share/wallpapers/esqueleto2.jpg
preload = /home/tsantos/.local/share/wallpapers/esqueleto.jpg

wallpaper = HDMI-A-1,/home/tsantos/.local/share/wallpapers/esqueleto2.jpg
wallpaper = DP-1,/home/tsantos/.local/share/wallpapers/esqueleto.jpg
